#!/usr/bin/env python3
"""Generate a ROS 2 occupancy grid map of the game field from its drawing.

Reads field dimensions in mm from config/field_config.yaml and writes a
map_server compatible map (PGM image + YAML metadata, in metres).

Only the walls are written into the map. Racks are moved during the game,
so they are handled by the costmap obstacle layer, not by the static map.

Usage (from the robot_navigation directory):
    python scripts/generate_map.py
    python scripts/generate_map.py --config config/field_config.yaml --preview

Requirements: numpy, pyyaml (pillow only for --preview).
"""

import argparse
from pathlib import Path

import numpy as np
import yaml

# map_server trinary pixel values
FREE = 254
OCCUPIED = 0
UNKNOWN = 205

PKG_DIR = Path(__file__).resolve().parent.parent


def mm_to_cells(value_mm: float, resolution_mm: float) -> int:
    """Convert a length in mm to a whole number of cells."""
    cells = value_mm / resolution_mm
    if abs(cells - round(cells)) > 1e-6:
        print(f"[warn] {value_mm} mm is not a multiple of the resolution "
              f"{resolution_mm} mm, rounded to {round(cells)} cells")
    return int(round(cells))


def build_grid(cfg: dict) -> tuple[np.ndarray, dict]:
    """Build the occupancy grid. Row 0 is the lowest y (flipped on save)."""
    field = cfg["field"]
    res = cfg["map"]["resolution_mm"]

    inner_x = mm_to_cells(field["length_mm"], res)
    inner_y = mm_to_cells(field["width_mm"], res)
    wall = max(1, mm_to_cells(field["wall_thickness_mm"], res))
    margin = mm_to_cells(cfg["map"]["margin_mm"], res)

    offset = margin + wall  # cells from the map edge to the inner corner
    width = inner_x + 2 * offset
    height = inner_y + 2 * offset

    grid = np.full((height, width), UNKNOWN, dtype=np.uint8)
    # walls: the ring between the inner field and the outer wall face
    grid[margin:height - margin, margin:width - margin] = OCCUPIED
    # free inner field
    grid[offset:offset + inner_y, offset:offset + inner_x] = FREE

    info = {
        "width": width,
        "height": height,
        "offset_cells": offset,
        "resolution_m": res / 1000.0,
    }
    return grid, info


def write_pgm(path: Path, grid: np.ndarray) -> None:
    """Write a binary PGM. Image row 0 is the top, i.e. the highest y."""
    image = np.flipud(grid)
    h, w = image.shape
    with open(path, "wb") as f:
        f.write(f"P5\n{w} {h}\n255\n".encode("ascii"))
        f.write(image.tobytes())


def write_map_yaml(path: Path, image_name: str, info: dict) -> None:
    """Write the map_server metadata. All values in metres."""
    res = info["resolution_m"]
    origin = -info["offset_cells"] * res  # field inner corner -> (0, 0)
    meta = {
        "image": image_name,
        "mode": "trinary",
        "resolution": round(res, 6),
        "origin": [round(origin, 6), round(origin, 6), 0.0],
        "negate": 0,
        "occupied_thresh": 0.65,
        "free_thresh": 0.25,
    }
    with open(path, "w", encoding="utf-8") as f:
        f.write("# Generated by scripts/generate_map.py - do not edit by hand\n")
        yaml.safe_dump(meta, f, sort_keys=False)


def write_preview(path: Path, grid: np.ndarray, info: dict, cfg: dict) -> None:
    """Save a PNG with zones and racks overlaid, for visual checking only."""
    from PIL import Image, ImageDraw

    scale = 4
    image = Image.fromarray(np.flipud(grid)).convert("RGB")
    image = image.resize((image.width * scale, image.height * scale),
                         Image.NEAREST)
    draw = ImageDraw.Draw(image)

    res_mm = cfg["map"]["resolution_mm"]
    off = info["offset_cells"]
    h = info["height"]

    def to_px(x_mm: float, y_mm: float) -> tuple[float, float]:
        col = off + x_mm / res_mm
        row = h - (off + y_mm / res_mm)
        return col * scale, row * scale

    def draw_rect(rect, color, label):
        x0, y0 = to_px(rect[0], rect[3])
        x1, y1 = to_px(rect[2], rect[1])
        draw.rectangle([x0, y0, x1, y1], outline=color, width=2)
        draw.text((x0 + 3, y0 + 3), label, fill=color)

    colors = {"start": (40, 90, 220), "destination": (30, 160, 60)}
    for name, rect in (cfg.get("zones") or {}).items():
        if rect:
            draw_rect(rect, colors.get(name, (120, 120, 120)), name)
    for name, rect in (cfg.get("racks") or {}).items():
        if rect:
            draw_rect(rect, (230, 140, 0), f"rack {name}")

    # field frame axes at the origin
    ox, oy = to_px(0, 0)
    draw.line([ox, oy, ox + 40, oy], fill=(220, 0, 0), width=2)
    draw.line([ox, oy, ox, oy - 40], fill=(0, 170, 0), width=2)
    draw.text((ox + 44, oy - 8), "x", fill=(220, 0, 0))
    draw.text((ox - 4, oy - 56), "y", fill=(0, 170, 0))

    image.save(path)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--config", type=Path,
                        default=PKG_DIR / "config" / "field_config.yaml")
    parser.add_argument("--out-dir", type=Path, default=PKG_DIR / "maps")
    parser.add_argument("--preview", action="store_true",
                        help="also save a PNG preview (needs pillow)")
    args = parser.parse_args()

    with open(args.config, encoding="utf-8") as f:
        cfg = yaml.safe_load(f)

    grid, info = build_grid(cfg)

    args.out_dir.mkdir(parents=True, exist_ok=True)
    name = cfg["map"]["name"]
    pgm_path = args.out_dir / f"{name}.pgm"
    yaml_path = args.out_dir / f"{name}.yaml"
    write_pgm(pgm_path, grid)
    write_map_yaml(yaml_path, pgm_path.name, info)

    res = info["resolution_m"]
    print(f"map:        {pgm_path}")
    print(f"metadata:   {yaml_path}")
    print(f"size:       {info['width']} x {info['height']} cells "
          f"({info['width'] * res:.3f} x {info['height'] * res:.3f} m)")
    print(f"resolution: {res} m/cell")
    print(f"field:      (0, 0) to ({cfg['field']['length_mm'] / 1000:.3f}, "
          f"{cfg['field']['width_mm'] / 1000:.3f}) m in the map frame")

    if args.preview:
        preview_path = args.out_dir / f"{name}_preview.png"
        write_preview(preview_path, grid, info, cfg)
        print(f"preview:    {preview_path}")


if __name__ == "__main__":
    main()
